"""Apply fitted Kriging model to calculate gridded gauge-radar correction
factors.

Input
-----
- Kriging model file generated by running fit_kriging_model.py

Output
------
The output is two arrays:
  1: gridded gauge-radar correction factors corr = log10(gauge / radar)
  2: Kriging variance of the correction factors

If regression-Kriging is used, the variance is not estimated and its set to
zero.

Two output formats are supported: GeoTIFF and compressed npz file.

Configuration files (in the config/<profile> directory)
-------------------------------------------------------
- compute_kriged_correction_factors.cfg
- radar_locations.yaml

Notes
-----
When applying this script, make sure that the target time is within the time
range used for model fitting. Kriging does not give good results when applied
to extrapolation. Also make sure that the output grid is sufficienly covered
by the gauge locations.
"""

import argparse
import configparser
from datetime import datetime
import os
import pickle

import numpy as np
import pyproj
import yaml

import importers
import exporters
import radar_archive
import util


def run(model, outtime, outfile, profile, nodata_mask, snowprob, snow_threshold=20):
    """
    Input arguments
    model -- Kriging model file
    outtime -- time stamp for output (YYYYmmddHHMM)
    outfile -- output file (without extension)
    profile -- configuration profile to use
    nodata_mask -- nodata mask
    snowprob -- probability of snow (0 - 100 %), numpy array
    snow_threshold -- snow threshold for masking out snowy pixels
    """

    # read configuration file
    config = configparser.ConfigParser()
    config.read(
        os.path.join("config", profile, "compute_kriged_correction_factors.cfg")
    )

    if config["kriging"]["method"] not in ["ordinary", "regression"]:
        raise ValueError(
            f"unsupported Kriging method {config['kriging']['method']}: choose 'ordinary' or 'regression'"
        )

    with open(os.path.join("config", profile, "radar_locations.yaml"), "r") as f:
        config_radarlocs = yaml.safe_load(f)
    radar_locs = util.read_radar_locations(config_radarlocs)

    # read Kriging model
    model = pickle.load(open(model, "rb"))

    projection = config["grid"]["projection"]

    # read configuration and initialize the output grid
    ll_lon = float(config["grid"]["ll_lon"])
    ll_lat = float(config["grid"]["ll_lat"])
    ur_lon = float(config["grid"]["ur_lon"])
    ur_lat = float(config["grid"]["ur_lat"])

    n_pixels_x = int(config["grid"]["n_pixels_x"])
    n_pixels_y = int(config["grid"]["n_pixels_y"])

    pr = pyproj.Proj(projection)
    ll_x, ll_y = pr(ll_lon, ll_lat)
    ur_x, ur_y = pr(ur_lon, ur_lat)

    grid_x = np.linspace(ll_x, ur_x, n_pixels_x + 1)
    grid_x += 0.5 * (grid_x[1] - grid_x[0])
    grid_x = grid_x[:-1]

    grid_y = np.linspace(ll_y, ur_y, n_pixels_y + 1)
    grid_y += 0.5 * (grid_y[1] - grid_y[0])
    grid_y = grid_y[:-1]

    ts = datetime.strptime(outtime, "%Y%m%d%H%M")
    if int(config["kriging"]["dimensions"]) == 3:
        grid_z = np.ones((1,)) * ts.timestamp()

    if config["kriging"]["method"] == "regression":
        regr_vars = config["regression"]["variables"].split(",")
        
    max_dist_to_nearest_radar = float(config["output"]["max_dist_to_nearest_radar"])
    # TODO: move this into separate module
    if max_dist_to_nearest_radar > 0 or (
        config["kriging"]["method"] == "regression" and "distance" in regr_vars
    ):
        # project radar locations to grid coordinates
        radar_xy = {}
        for radar in radar_locs.keys():
            x, y = pr(radar_locs[radar][0], radar_locs[radar][1])
            radar_xy[radar] = (x, y)

    # compute gridded distances to the nearest radar for the regression model
    radar_dist_grid = util.compute_gridded_distances_to_nearest_points(
        ll_x,
        ll_y,
        ur_x,
        ur_y,
        int(config["grid"]["n_pixels_x"]),
        int(config["grid"]["n_pixels_y"]),
        radar_xy,
    )
    
    if config["kriging"]["method"] == "ordinary":
        if int(config["kriging"]["dimensions"]) == 2:
            zvalues, sigmasq = model.execute("grid", grid_x, grid_y)
        else:
            zvalues, sigmasq = model.execute("grid", grid_x, grid_y, grid_z)

        if int(config["kriging"]["dimensions"]) == 3:
            zvalues = zvalues[0, :]
            sigmasq = sigmasq[0, :]

        if isinstance(zvalues, np.ma.MaskedArray):
            zvalues.set_fill_value(np.nan)
            sigmasq.set_fill_value(np.nan)

        xp = model.X_ORIG
        yp = model.Y_ORIG
    else:
        regr_var_values = [[] for i in range(len(regr_vars))]

        for regr_var in regr_vars:
            # TODO: move these into separate module
            if regr_var == "distance":
                p = radar_dist_grid.flatten()[:, np.newaxis]
            elif regr_var == "radar_rain":
                config_ds = configparser.ConfigParser(interpolation=None)
                config_ds.read(os.path.join("config", args.profile, "datasources.cfg"))
                config_radar = config_ds["radar"]

                browser = radar_archive.Browser(
                    config_radar["root_path"],
                    config_radar["path_fmt"],
                    config_radar["fn_pattern"],
                    config_radar["fn_exts"].split(","),
                    0,
                )

                try:
                    fn = browser.listfiles(ts)
                    
                    if os.path.exists(fn[0][0]):
                        fn = fn[0][0]
                        print(f"Found radar file {os.path.basename(fn)}")
                except FileNotFoundError:
                    print(f"Radar file not found for {ts}")

                importer = importers.get_method(config_radar["importer"])
                radar_rain, _ = importer(fn, **config_ds["radar_importer_kwargs"])
                radar_rain[~np.isfinite(radar_rain)] = 0
                # TODO: check that distance and radar rain rate files are not upside down
                radar_rain = np.flipud(radar_rain)
                p = radar_rain.flatten()[:, np.newaxis]
        
        n_x = len(grid_x)
        n_y = len(grid_y)
        grid_x, grid_y = np.meshgrid(grid_x, grid_y)
        if int(config["kriging"]["dimensions"]) == 2:
            xp = np.column_stack([grid_x.flatten(), grid_y.flatten()])
        else:
            xp = np.column_stack(
                [grid_x.flatten(), grid_y.flatten(), grid_z[0] * np.ones(grid_x.size)]
            )
        zvalues = model.predict(p, xp).reshape((n_y, n_x))
        sigmasq = np.zeros(zvalues.shape)

        xp = model.krige.model.X_ORIG
        yp = model.krige.model.Y_ORIG

    gauge_xy = {}
    for i in range(len(xp)):
        gauge_xy[i] = (xp[i], yp[i])

    if max_dist_to_nearest_radar > 0:
        radar_dist_mask = radar_dist_grid < max_dist_to_nearest_radar
    else:
        radar_dist_mask = np.ones((n_pixels_y, n_pixels_x), dtype=bool)

    max_dist_to_nearest_gauge = float(config["output"]["max_dist_to_nearest_gauge"])
    if max_dist_to_nearest_gauge > 0:
        gauge_dist_grid = util.compute_gridded_distances_to_nearest_points(
            ll_x,
            ll_y,
            ur_x,
            ur_y,
            int(config["grid"]["n_pixels_x"]),
            int(config["grid"]["n_pixels_y"]),
            gauge_xy,
        )

        gauge_dist_mask = gauge_dist_grid < max_dist_to_nearest_gauge
    else:
        gauge_dist_mask = np.ones((n_pixels_y, n_pixels_x), dtype=bool)
        
    exclude_mask = radar_dist_mask

    if config["snowprob"]["use_snowprob_obs"]:
        mask = (snowprob > snow_threshold) & (~np.isnan(snowprob))
        zvalues[mask] = 0.0
        sigmasq[mask] = 0.0
    
    if float(config["output"]["mask_blur_distance"]) > 0:
        weights = util.compute_mask_boundary_weights(
            exclude_mask, float(config["output"]["mask_blur_distance"])
        )
        zvalues *= weights
        sigmasq *= weights
        zvalues[weights == 0] = 0
        sigmasq[weights == 0] = 0
    else:
        zvalues[~exclude_mask] = 0
        sigmasq[~exclude_mask] = 0

    print("zvalues min, max: ", np.nanmin(zvalues), np.nanmax(zvalues))       
        
    if config["output"]["type"] == "geotiff":
        pr = pyproj.Proj(config["grid"]["projection"])

        ll_x, ll_y = pr(config["grid"]["ll_lon"], config["grid"]["ll_lat"])
        ur_x, ur_y = pr(config["grid"]["ur_lon"], config["grid"]["ur_lat"])

        bounds = [ll_x, ll_y, ur_x, ur_y]
        out_rasters = np.stack([zvalues, sigmasq])
        fn = outfile + ".tif"
        exporters.export_geotiff(fn, zvalues, config["grid"]["projection"], bounds)

    elif config["output"]["type"] == "numpy":
        np.savez_compressed(outfile, corr=zvalues.filled(), corr_var=sigmasq.filled())
    else:
        raise ValueError(
            f"Output format {config['output']['type']} not supported. The valid options are 'geotiff' and 'numpy'"
        )
