name: radargaugemerging
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - git
  - h5py
  - matplotlib
  - numpy
  - pillow
  - pip
  - pykrige
  - pyproj
  - scipy
  - pip:
    - git+https://github.com/karjaljo/hiisi.git
